# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - run: pnpm i
      - run: pnpm run dev:build
      - run: pnpm run build
      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v2.2.0
        with:
          token: ${{ secrets.NPM_TOKEN }}
